### ISSUE TITLE
Fail to start 

### ISSUE THREAD

**Issue by jarlarntzen** [zlsa/piper-archer#1] opened 2015-03-21 11:59 UTC
Hi. I downloaded the latest zip from github.io yesterday
http://zlsa.github.io/piper-archer/#download

Put the folder **pa28-181** into /usr/share/games/flightgear/Aircraft as instructed

This is what I get in the terminal when trying to start FG with the Piper Archer CX

```
jarl@jarl-Precision-WorkStation-T3400:~$ fgfs --aircraft=piper-archer-cx
Enabling ATI viewport hack
Starting automatic scenery download/synchronization. Using built-in SVN support. Directory: '/home/jarl/.fgfs/TerraSync'.
default catalog not found, installing 'org.flightgear.default' from 'http://fgfs.goneabitbursar.com/pkg/3.5.0/default-catalog.xml'.
can't find "Effects/model-interior.eff"
can't find base effect Effects/model-interior
can't find base effect Models/Effects/interior
can't find "Effects/model-interior.eff"
can't find base effect Effects/model-interior
can't find base effect Models/Effects/interior
can't find "Effects/model-interior.eff"
can't find base effect Effects/model-interior
can't find base effect Models/Effects/interior
can't find "Effects/model-interior.eff"
can't find base effect Effects/model-interior
can't find base effect Models/Effects/interior
can't find "Effects/model-interior.eff"
can't find base effect Effects/model-interior
can't find base effect Models/Effects/interior
Segmentation fault (core dumped)
```

Then the thing crashes.

---
## Further information

jarl@jarl-Precision-WorkStation-T3400:~$ fgfs --version
FlightGear version: 3.5.0
Revision: none
Build-Id: none
FG_ROOT=/usr/share/games/flightgear
FG_HOME=/home/jarl/.fgfs
FG_SCENERY=
SimGear version: 3.5.0
PLIB version: 185

**Comment by zlsa** [comment] 2015-03-21 17:27
The folder should be named `piper-archer`, not `pa28-181`. (If it's `pa28-181`, the aircraft itself will be visible because of the `-set.xml` file but it won't be able to find any of the other files.)

**Comment by jarlarntzen** [comment] 2015-03-21 20:29
Ok. Sounds great. I'll try it when I get back home.

I'd strongly suggest, though, to either the folder name inside the downloadable zip-file or the instructions for installation here:
http://zlsa.github.io/piper-archer/#download as they clearly instruct me to "2. Unzip the file to `$FG_ROOT/Aircraft/`" There's no explicit instruction to create or rename the folder to **piper-archer**, although step 4 gives some hint of that.

Also, is there an **absolute** requirement to put `$FG_ROOT/Aircraft` or is it equally OK to put the folder into any path defined to be `$FG_AIRCRAFT`

**Comment by zlsa** [comment] 2015-03-22 01:43
The older releases use `pa28-181` but anything recent should be `piper-archer` (I renamed it in the middle... it was a bad idea in hindsight.)

No, it should be like any other aircraft; those instructions are just there because I see so many people confused about how to install aircraft.

**Comment by zlsa** [comment] 2015-04-18 01:17
Duplicate of #2.

**Closed as completed by zlsa** 2015-04-18 01:17 UTC
